### ISSUE TITLE
Josev exificient .jar support for ACDP

### ISSUE THREAD

**Issue by cienporcien** [EVerest/EVerest-archived#118]
I'm working on adding ACDP support to 15118-20. I'm starting with the evcc side so I can test the secc side. I've asked this same question in Josev, but perhaps someone knows the answer here:

In Josev, when encoding ACDP_VehiclePositioningReq, I get the following, which I think indicates that the Exificient .jar file hasn't been built with ACDP support:

INFO 2023-11-24 10:23:16,384 - iso15118.shared.exi_codec (255): Message to encode **(ns=urn:iso:std:iso:15118:-20:ACDP): {"ACDP_VehiclePositioningReq": {"Header": {"SessionID": "45E3EE715D0ACE6A", "TimeStamp": 1700817781}, "EVMobilityStatus": true, "EVPositioningSupport": false}}**
ERROR 2023-11-24 10:23:16,398 - iso15118.shared.exi_codec (260): EXIEncodingError in urn:iso:std:iso:15118:-20:ACDP with {"ACDP_VehiclePositioningReq": {"Header": {"SessionID": "45E3EE715D0ACE6A", "TimeStamp": 1700817781}, "EVMobilityStatus": true, "EVPositioningSupport": false}}: Unknown error: javax.xml.bind.UnmarshalException

    with linked exception:
    [java.lang.RuntimeException:
    Exception Description: A descriptor with default root element ACDP_VehiclePositioningReq was not found in the project]

Any ideas on how to remedy this? Perhaps using a different exi encoder? Rebuilding exificient? 

Best regards,
Roger

**Comment by SebaLukas** [comment]
Hi Roger,

great that you are working on ISO15118-20 ACDP.

It also seems to me that the EXICodec.jar cannot encode or decode ACDP messages.
According to a service and features table in the Josev Readme.md, the Iso15118 implementation of Josev does not support ACDP, ACDP BPT and WPT.

Since unfortunately only the JAR and not the source code of the EXICodec.jar can be found in the Josev Community Edition repo, it will be very difficult to extend the JAR with ACDP.
It might also be possible to extend Exificient. But I don't know enough about that.

One possibility would be to extend EVerest [cbexigen](https://github.com/EVerest/cbexigen) to generate c code that can also encode and decode the ACDP EXI messages. The ISO15118-20 CommonMessages, DC & AC (both with BPT) are already supported and you can already encode and decode them as EXI messages.
In this case, however, all the ISO20 message structs would have to be converted to Json, e.g. using cJson, as the Josev python code passes the ISO messages as Json/dict to the EXICodec.jar.
This could also be a great project for the EVerest community.

Perhaps there will also be feedback from Switch when they officially support ACDP.

I hope I could help you with this.

Best regards
Sebastian

**Comment by cienporcien** [comment]
Hi Sebastian,
Thanks for your quick reply on this. Over at the Switch repo, it seems to be a common request for them to open up their EXICodec.jar project, but so far it seems they don't want to for some reason. I'll look into adapting cbexigen to replace it with your above hints, but may need some help at some point.
Best regards,
Roger

**Comment by slachiewicz** [comment]
I don't think this is the way to go (to stay with Java while all we have in python).
Opensourcing may help other Java projects.
Here we need something more native, like proposed Rust implementation.

**Comment by cienporcien** [comment]
Sorry, I'm confused. Are you saying EVerest should implement the evcc side in Rust? Also a EXIgen in Rust? It looks like Switch has a proprietary Rust EXIcodec for their "professional" edition.

**Comment by SebaLukas** [comment]
@cienporcien I have been working for months in my free time on an EXI parser that you can import into your cargo project or Josev as a Rust crate or as a Python module. For this I use the generated c code from cbexigen and the Rust serde_json crate. But I will definitely need more time, as I am simply doing this in my spare time.
But before we do double work in the near future, I would like to suggest something else:

It would be really awesome if we could get the EVerest community to work together on an alternative for the ExiCodec.jar. I think we could find a few people who would be interested in working on it.

I don't know what your timeline is for ACDP? But the plan for early 2024 is to have subgroups for EVerest. One of them is the Car<->Charger Communication group. And I think that this alternative implementation would be a good first project for this group.

I would suggest that we continue the discussion in the EVerest mailing list until the subgroup exists. I'll open a topic for this.

@slachiewicz Sorry, I don't quite understand what you mean. Can you describe it in more detail?

**Comment by barsnick** [comment]
> One possibility would be to extend EVerest [cbexigen](https://github.com/EVerest/cbexigen) to generate c code that can also encode and decode the ACDP EXI messages.

This is already possible. A branch with the config file which adds ACDP (and WPT) is here:
https://github.com/EVerest/cbexigen/tree/feature/WPT_and_ACDP
with this commit:
https://github.com/EVerest/cbexigen/commit/6e49b666f1fc1a0c16ed13e6967a25c6f955b5bc

**Comment by cienporcien** [comment]
I'll give it a go.

**Comment by krealyt** [comment]
Having seen https://github.com/EVerest/cbexigen/pull/63 - I think that we can close this issue ...

If I am wrong, feel free to re-open this issue (and decrease my karma budget).
