### ISSUE TITLE
Building OCPP library standalone

### ISSUE THREAD

**Issue by movhdi** [EVerest/EVerest-archived#58]
Hello. I am trying to have libocpp built and I am not able to resolve all dependencies. My goal is to get involved in and start contributing so I do not want to manipulate any line of code in the cmake structure of the project.
At first, I cloned libocpp repository, standalone. Some of the dependencies to external libraries such as "boost" are straightforward and  resoluble. However, There are some dependencies to "liblog" and "everest-framework" as <date.hpp> and <logging.hpp>, <nlohmann/json.hpp> and some others I have difficulty resolving inculsion problem.
I suppressed errors due to <nlohmann/json.hpp> by using the following command:
> $ sudo apt-get install nlohmann-json3-dev

But I am not sure this is the correct way of doing that because I do not know which version is getting installed using this command.
Also, I resolved the problem of websocketpp inclusion by just installing the lib using following commands.

> $ git clone git://github.com/zaphoyd/websocketpp.git
> $ cd websocketpp
> $ cmake .
> $ sudo make install

Secondly, I cloned the whole EVerest project step by step just like said on everest-core repository in hope that cmake will find other internal libraries and resolve the complaints from compiler. The issue is persisting. 
I am using VSCODE, in Ubuntu.
Could you please help me satisfy the unhappy squiggly red lines in my vscode?

**Comment by corneliusclaussen** [comment]
Hi,

I would recommend to start with the full EVerest instead of the ocpp library only. What output do you get when building everest-core?

**Comment by lisi0820** [comment]
> Hi,
> 
> I would recommend to start with the full EVerest instead of the ocpp library only. What output do you get when building everest-core?

When I was trying to build the everst-core I got the following error, 
`/everest-workspace/everest-core/modules/SerialCommHub/main/serial_communication_hubImpl.cpp:349:43: error: ‘class everest::modbus::ModbusRTUClient’ has no member named ‘read_input_register’; did you mean ‘read_holding_register’?
  349 |                 response = modbus_client->read_input_register(
      |                                           ^~~~~~~~~~~~~~~~~~~
      |                                           read_holding_register
In file included from /usr/include/c++/11/bits/shared_ptr_base.h:59,
                 from /usr/include/c++/11/bits/shared_ptr.h:53,
                 from /usr/include/c++/11/condition_variable:43,
                 from /usr/include/c++/11/future:39, 
`
It's that because I didn't get the newest version?
Thanks

**Comment by corneliusclaussen** [comment]
main in everest-core is currently broken, will fix that tomorrow

**Comment by movhdi** [comment]
Dear Cornelius, 
I bulit the EVerest completely without any error. I opened then my VScode again for the newest libocpp clone, the issue still exists. Would you please help me with the next step?

**Comment by Pietfried** [comment]
Hi, 

can you describe more specifically what error/output you get when building libocpp standalone?

**Comment by movhdi** [comment]
Dear Piet, 
Before building EVerest, some of the includes were unknown, such is <liblog.h>, <time.h>, and <tz.h>. After I built EVerest, there is just json_schemas.hpp missing seemingly. The squiggly line is only under json_schemas.hpp inclusion.

**Comment by Pietfried** [comment]
Hi, am I correct that you can build liboccp standalone successfully and only have problems with vscode not finding the import? The dependencies for nlohmann and others are located inside libocpp/build/_deps so you would need to configure your vscode so that it finds these dependencies.

**Comment by lisi0820** [comment]
Hi,
So I have created my own charger config file using the admin panel. However, I could only access this config file within the admin panel, my question is where is that config saved at? and what's the relationship between the config files and the nodered.json in the node-red?

It seems like I could only use the nodered/ui to simulate two charging process so far, config-sil-flow.json and config-sil-two-evse-flow.json.
In order to simulate my own charging process do I need to convert that config file to a nodered.json?

**Comment by corneliusclaussen** [comment]
Hi EvanLi0820, your question seems to be unrelated to this thread. Can you post it on the mailinglist instead? https://lists.lfenergy.org/g/everest
