### ISSUE TITLE
Workspace docker-mqtt.code-workspace location

### ISSUE THREAD

**Issue by AndyChriss123** [EVerest/EVerest-archived#59]
Hello and thank you for your help!

This is stated in everest-utils/docker readme. 

"Start vscode, open the workspace docker-mqtt.code-workspace and install suggested extensions. Open a shell in sub-directory docker and run (might take while for the first run):"

I'm sorry but where exactly can I find this workspace that I should load? Could you please clarify as briefly as possible, I wont ask for much of an explanation but it sounds important..

**Comment by AndyChriss123** [comment]
Also, could you please clarify for me whether if this is the best place to post such questions or not? Should I turn to the mailing list instead? I want to be as less of a bother as possible while making sure that as many people as possible can benefit from the answers that you provide.
It will take a while until we can actually bring real benefits towards actively helping improve EVerest but inevitably we will eventually get there with your help. Thank you for what you are doing.
Good luck and all the best.

**Comment by corneliusclaussen** [comment]
Hi!

The mailing list is probably a better place for generic questions as more people are reading it and you will get a reply much faster. The readme seems out of date here, we will try to update it. You can also run EVerest without the docker workspace, just follow: https://everest.github.io/nightly/general/03_detail_pre_setup.html
Then you can just open the workspace/everest-core folder in vscode.
In order to start the sil you need an mqtt broker such as mosquitto, you can install that either locally via your package manager or use docker:  docker-compose up mqtt-server in the utils/docker folder.

**Comment by AndyChriss123** [comment]
Ok, I was able to launch EVerest without issue. I was just thinking that maybe I was missing out on some features or configurations. Thank you for taking the time to answer!
All the best.
